import type { CatalogCategoryKey } from "./categories";

export type BrandKey = "DJI" | "GoPro" | "Autel";

export type ProductSpec = { label: string; value: string };

export type BriefIcon = "camera" | "flight" | "distance" | "video";

export type BriefSpec = {
  icon: BriefIcon;
  label: string;
  value: string;
};

export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: BrandKey;
  category: CatalogCategoryKey;
  badge: string;
  priceBYN: number;
  shortDescription: string;
  longDescription: string;
  briefSpecs: BriefSpec[];
  techSpecs: ProductSpec[];
};

const cardImages = import.meta.glob("../assets/img/catalog/*/*.png", {
  eager: true,
  import: "default",
}) as Record<string, string>;

const pageImages = import.meta.glob("../assets/img/product_page/*/*.png", {
  eager: true,
  import: "default",
}) as Record<string, string>;

const catalogFolderByCategory: Record<CatalogCategoryKey, string> = {
  drones: "drones",
  cameras: "cameras",
  accessories: "accesories",
  microphones: "micro",
};

export const slugify = (name: string): string =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const lookupImage = (record: Record<string, string>, folder: string, filename: string): string | null => {
  const decoded = `/${folder}/${filename}`;
  for (const [path, url] of Object.entries(record)) {
    if (decodeURIComponent(path).endsWith(decoded)) return url;
  }
  return null;
};

export const getCardImage = (product: Product): string => {
  const folder = catalogFolderByCategory[product.category];
  return lookupImage(cardImages, folder, `${product.name}.png`) ?? "";
};

export const getPageImages = (product: Product): string[] => {
  const folder = catalogFolderByCategory[product.category];
  const fallback = getCardImage(product);
  return [1, 2, 3].map(
    (idx) => lookupImage(pageImages, folder, `${product.name}_page_${idx}.png`) ?? fallback,
  );
};

const products: Product[] = [
  {
    id: "drones-1",
    slug: "autel-alpha",
    name: "Autel Alpha",
    brand: "Autel",
    category: "drones",
    badge: "NEW",
    priceBYN: 83151,
    shortDescription: "Autel Alpha для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "Autel Alpha для аэросъемки и сложных условий. Стабильный полет и точная навигация. Флагман линейки Autel Robotics с тремя осевым подвесом, 6K HDR-камерой и обновлённой системой обхода препятствий в шести направлениях. Алюминиевый корпус, защита IP43 и двойные аккумуляторы обеспечивают до 45 минут полёта в дождь и сильный ветер до 17 м/с. Передача видео SkyLink 3.0 на расстояние до 20 км и поддержка RTK-модуля позволяют использовать Alpha как универсальный инструмент для съёмок, инспекций и поисково-спасательных операций.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "1\" CMOS · 50 МП" },
      { icon: "flight", label: "Полёт", value: "до 45 минут" },
      { icon: "distance", label: "Дистанция", value: "до 20 км (SkyLink 3.0)" },
      { icon: "video", label: "Видео", value: "6K HDR · 60 к/с" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "1860 г" },
      { label: "Размер в сложенном виде", value: "245 × 132 × 110 мм" },
      { label: "Максимальная высота полёта", value: "7000 м" },
      { label: "Максимальная скорость", value: "27 м/с" },
      { label: "Сенсор камеры", value: "1\" CMOS, 50 МП" },
      { label: "Объектив", value: "24 мм, f/2.0–f/11" },
      { label: "Видео", value: "6K при 60 к/с, 4K при 120 к/с" },
      { label: "Битрейт", value: "до 200 Мбит/с (H.265)" },
      { label: "Гимбал", value: "3-осевой стабилизатор" },
      { label: "Обход препятствий", value: "Всенаправленный (6 датчиков)" },
      { label: "Аккумулятор", value: "9000 мА·ч, 23.1 В" },
      { label: "Передача видео", value: "SkyLink 3.0, до 20 км" },
      { label: "Класс защиты", value: "IP43" },
      { label: "Рабочая температура", value: "−20 ... +50 °C" },
      { label: "Внутренняя память", value: "128 ГБ + microSD до 1 ТБ" },
    ],
  },
  {
    id: "drones-2",
    slug: "autel-evo-2-pro-v3",
    name: "Autel EVO 2 Pro V3",
    brand: "Autel",
    category: "drones",
    badge: "PRO",
    priceBYN: 19358,
    shortDescription: "Autel EVO 2 Pro V3 для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "Autel EVO 2 Pro V3 для аэросъемки и сложных условий. Стабильный полет и точная навигация. Дюймовая матрица Sony, переменная диафрагма f/2.8–f/11 и 10-битная запись A-LOG раскрывают потенциал коммерческой съёмки в любых сценах. До 40 минут полёта, обновлённая система обхода препятствий и зашифрованный канал передачи SkyLink 2.0 на 15 км делают модель надёжным инструментом для профессионального аэрофотографа.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "1\" Sony CMOS · 20 МП" },
      { icon: "flight", label: "Полёт", value: "до 40 минут" },
      { icon: "distance", label: "Дистанция", value: "до 15 км (SkyLink 2.0)" },
      { icon: "video", label: "Видео", value: "6K · 30 к/с, 10-bit A-LOG" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "1191 г" },
      { label: "Размеры", value: "397 × 314 × 113 мм" },
      { label: "Максимальная высота полёта", value: "7000 м" },
      { label: "Максимальная скорость", value: "20 м/с" },
      { label: "Сенсор камеры", value: "1\" CMOS, 20 МП" },
      { label: "ISO видео", value: "100–6400" },
      { label: "Видео", value: "6K при 30 к/с, 4K при 60 к/с" },
      { label: "Битрейт", value: "до 120 Мбит/с (H.265)" },
      { label: "Цветовой профиль", value: "A-LOG, HDR Video" },
      { label: "Обход препятствий", value: "12 датчиков, всенаправленный" },
      { label: "Аккумулятор", value: "7100 мА·ч, 11.55 В" },
      { label: "Передача видео", value: "SkyLink 2.0, до 15 км" },
      { label: "Защита от ветра", value: "до 12 м/с" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
      { label: "Внутренняя память", value: "8 ГБ + microSD до 256 ГБ" },
    ],
  },
  {
    id: "drones-3",
    slug: "autel-evo-enterprice-v3",
    name: "Autel EVO Enterprice V3",
    brand: "Autel",
    category: "drones",
    badge: "NEW",
    priceBYN: 36951,
    shortDescription: "Autel EVO Enterprice V3 для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "Autel EVO Enterprice V3 для аэросъемки и сложных условий. Стабильный полет и точная навигация. Сменные модули — широкоугольная камера 50 МП, тепловизор и лазерный дальномер — превращают компактный квадрокоптер в полноценный инструмент для инспекций и поисково-спасательных миссий. До 42 минут полёта, защита IP43 и режим RTK гарантируют сантиметровую точность позиционирования даже на сложных объектах.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "Сменные модули (50 МП / IR / LiDAR)" },
      { icon: "flight", label: "Полёт", value: "до 42 минут" },
      { icon: "distance", label: "Дистанция", value: "Точность 1 см + 1 ppm" },
      { icon: "video", label: "Видео", value: "8K · 30 к/с" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "1999 г" },
      { label: "Размеры", value: "427 × 384 × 154 мм" },
      { label: "Максимальная высота полёта", value: "7000 м" },
      { label: "Максимальная скорость", value: "23 м/с" },
      { label: "Сенсор камеры", value: "1/1.28\" CMOS, 50 МП" },
      { label: "Видео", value: "8K при 30 к/с, 4K при 60 к/с" },
      { label: "Тепловизор (модуль)", value: "640×512, 30 Гц" },
      { label: "Обход препятствий", value: "Всенаправленный" },
      { label: "Аккумулятор", value: "8070 мА·ч, 14.88 В" },
      { label: "Передача видео", value: "Autel SkyLink, до 15 км" },
      { label: "RTK", value: "Сантиметровая точность" },
      { label: "Прожектор", value: "Светодиодный, 4 уровня" },
      { label: "Громкоговоритель", value: "100 дБ на 1 м" },
      { label: "Защита", value: "IP43" },
      { label: "Рабочая температура", value: "−20 ... +50 °C" },
    ],
  },
  {
    id: "drones-4",
    slug: "autel-evo-max-4t",
    name: "Autel EVO Max 4T",
    brand: "Autel",
    category: "drones",
    badge: "MAX",
    priceBYN: 83151,
    shortDescription: "Autel EVO Max 4T для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "Autel EVO Max 4T для аэросъемки и сложных условий. Стабильный полет и точная навигация. Четырёхдатчиковый гимбал объединяет широкоугольную и теле-камеры, тепловизор 640×512 и лазерный дальномер на 1200 м. Система автономной навигации A-Mesh работает даже без GPS, а уникальный режим Mission Pack позволяет планировать инспекции инфраструктуры с точностью до миллиметра.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "4 в 1: Wide / Tele / IR / Laser" },
      { icon: "flight", label: "Полёт", value: "до 42 минут" },
      { icon: "distance", label: "Дистанция", value: "до 1200 м (лазер)" },
      { icon: "video", label: "Видео", value: "Гибридный зум до 160×" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "1620 г" },
      { label: "Размеры", value: "490 × 423 × 167 мм" },
      { label: "Максимальная высота полёта", value: "7000 м" },
      { label: "Максимальная скорость", value: "23 м/с" },
      { label: "Широкоугольная камера", value: "1/1.28\" CMOS, 50 МП" },
      { label: "Телекамера", value: "1/2\" CMOS, 48 МП, 10× зум" },
      { label: "Тепловизор", value: "640×512, частота 30 Гц" },
      { label: "Лазерный дальномер", value: "до 1200 м, точность ±0.2 м" },
      { label: "Видео", value: "4K при 30 к/с, H.265" },
      { label: "Обход препятствий", value: "Всенаправленный (LiDAR + Vision)" },
      { label: "Аккумулятор", value: "8070 мА·ч, 14.88 В" },
      { label: "Передача видео", value: "Autel SkyLink 3.0, до 20 км" },
      { label: "Режим без GPS", value: "A-Mesh, VIO" },
      { label: "Защита", value: "IP43" },
      { label: "Рабочая температура", value: "−20 ... +50 °C" },
    ],
  },
  {
    id: "drones-5",
    slug: "autel-evo-rtk-series-v3",
    name: "Autel EVO RTK Series V3",
    brand: "Autel",
    category: "drones",
    badge: "RTK",
    priceBYN: 39723,
    shortDescription: "Autel EVO RTK Series V3 для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "Autel EVO RTK Series V3 для аэросъемки и сложных условий. Стабильный полет и точная навигация. Встроенный RTK-модуль и поддержка PPK обеспечивают сантиметровую точность позиционирования, что делает дрон идеальным решением для геодезии, картографии и аэрофотограмметрии. Совмещение камеры 20 МП с глобальным затвором и автоматических маршрутов позволяет получить готовые ортофотопланы прямо в воздухе.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "1\" CMOS, 20 МП, глоб. затвор" },
      { icon: "flight", label: "Полёт", value: "до 38 минут" },
      { icon: "distance", label: "Дистанция", value: "до 15 км (SkyLink)" },
      { icon: "video", label: "Видео", value: "4K при 30 к/с, RTK 1 см + 1 ppm" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "1350 г" },
      { label: "Размеры", value: "397 × 314 × 113 мм" },
      { label: "Максимальная высота полёта", value: "7000 м" },
      { label: "Максимальная скорость", value: "20 м/с" },
      { label: "Сенсор камеры", value: "1\" CMOS, 20 МП" },
      { label: "Объектив", value: "f/2.8, 35 мм экв. фокусное" },
      { label: "Видео", value: "4K при 30 к/с, H.264/H.265" },
      { label: "RTK / PPK", value: "Поддерживается" },
      { label: "Сантиметровая точность", value: "1 см + 1 ppm (RTK FIX)" },
      { label: "Обход препятствий", value: "12 датчиков" },
      { label: "Аккумулятор", value: "7100 мА·ч, 11.55 В" },
      { label: "Передача видео", value: "Autel SkyLink, до 15 км" },
      { label: "Поддержка миссий", value: "Waypoint, Mapping, Oblique" },
      { label: "Внутренняя память", value: "8 ГБ + microSD до 256 ГБ" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "drones-6",
    slug: "autel-fpv-speedster",
    name: "Autel FPV Speedster",
    brand: "Autel",
    category: "drones",
    badge: "FPV",
    priceBYN: 12003,
    shortDescription: "Autel FPV Speedster для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "Autel FPV Speedster для аэросъемки и сложных условий. Стабильный полет и точная навигация. Лёгкий и быстрый FPV-дрон с разгоном до 150 км/ч и низкой задержкой передачи изображения 28 мс. 4K-камера с трёхосной стабилизацией пишет кадры даже на максимальных скоростях, а очки SkyView дают захватывающий обзор с углом 155°.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "4K · 120 к/с" },
      { icon: "flight", label: "Полёт", value: "до 20 минут" },
      { icon: "distance", label: "Дистанция", value: "до 150 км/ч (макс.)" },
      { icon: "video", label: "Видео", value: "Задержка 28 мс, SkyView 155°" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "612 г" },
      { label: "Размеры", value: "245 × 245 × 76 мм" },
      { label: "Максимальная скорость", value: "42 м/с (150 км/ч)" },
      { label: "Ускорение 0-100 км/ч", value: "1.7 с" },
      { label: "Камера", value: "1/1.7\" CMOS, 4K при 120 к/с" },
      { label: "Гимбал", value: "3-осевой механический" },
      { label: "Видео", value: "до 200 Мбит/с, H.265" },
      { label: "Задержка передачи", value: "28 мс" },
      { label: "Аккумулятор", value: "2200 мА·ч, 14.8 В" },
      { label: "Полётное время", value: "до 20 минут" },
      { label: "Очки", value: "SkyView, FOV 155°, 1080p/120" },
      { label: "Режимы полёта", value: "Normal / Sport / Manual (Acro)" },
      { label: "Радиус действия", value: "до 10 км" },
      { label: "Защита от ветра", value: "до 10 м/с" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "drones-7",
    slug: "autel-industrial",
    name: "Autel Industrial",
    brand: "Autel",
    category: "drones",
    badge: "PRO",
    priceBYN: 50811,
    shortDescription: "Autel Industrial для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "Autel Industrial для аэросъемки и сложных условий. Стабильный полет и точная навигация. Тяжёлая промышленная платформа с двумя аккумуляторами, защитой IP55 и поддержкой подвесов до 1.5 кг. Подходит для строительства, энергетики и логистики: совмещает функции инспекции, доставки и точечного картографирования благодаря интеграции RTK и поддержке СДК Autel SDK.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "Сменные подвесы Camera / IR / LiDAR" },
      { icon: "flight", label: "Полёт", value: "до 55 минут" },
      { icon: "distance", label: "Дистанция", value: "до 20 км (SkyLink)" },
      { icon: "video", label: "Видео", value: "Полезная нагрузка до 1.5 кг" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "3450 г" },
      { label: "Размеры", value: "650 × 645 × 195 мм" },
      { label: "Максимальная высота", value: "5000 м" },
      { label: "Максимальная скорость", value: "23 м/с" },
      { label: "Полезная нагрузка", value: "до 1500 г" },
      { label: "Аккумуляторы", value: "Двойные, горячая замена" },
      { label: "Полётное время", value: "до 55 минут" },
      { label: "Передача видео", value: "Autel SkyLink, до 20 км" },
      { label: "Класс защиты", value: "IP55" },
      { label: "RTK / PPK", value: "Сантиметровая точность" },
      { label: "Поддержка SDK", value: "Autel SDK / MAVLink" },
      { label: "Обход препятствий", value: "Всенаправленный" },
      { label: "Прожектор", value: "Светодиодный 80 лм" },
      { label: "Громкоговоритель", value: "120 дБ" },
      { label: "Рабочая температура", value: "−20 ... +50 °C" },
    ],
  },
  {
    id: "drones-8",
    slug: "dji-air-3s",
    name: "DJI Air 3S",
    brand: "DJI",
    category: "drones",
    badge: "NEW",
    priceBYN: 10155,
    shortDescription: "DJI Air 3S для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "DJI Air 3S для аэросъемки и сложных условий. Стабильный полет и точная навигация. Двойная камера сочетает дюймовый сенсор с широкоугольным объективом и среднефокусную камеру 3×, обеспечивая профессиональное качество фото 50 МП и видео 4K/120. LiDAR-датчик ночного обзора обходит препятствия даже в темноте, а технология O4+ передаёт изображение на 20 км.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "1\" Wide · 1/1.3\" Tele 3×" },
      { icon: "flight", label: "Полёт", value: "до 45 минут" },
      { icon: "distance", label: "Дистанция", value: "—" },
      { icon: "video", label: "Видео", value: "4K · 120 к/с, D-Log M" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "724 г" },
      { label: "Размеры", value: "266 × 326 × 105 мм" },
      { label: "Максимальная скорость", value: "21 м/с" },
      { label: "Защита от ветра", value: "до 12 м/с" },
      { label: "Wide-камера", value: "1\" CMOS, 24 мм, f/1.8" },
      { label: "Tele-камера", value: "1/1.3\" CMOS, 70 мм, f/2.8" },
      { label: "Фото", value: "50 МП, HDR, RAW (DNG)" },
      { label: "Видео", value: "4K при 120 к/с, 10-bit D-Log M" },
      { label: "Цветовой профиль", value: "D-Log, D-Log M, HLG" },
      { label: "Обход препятствий", value: "Всенаправленный + LiDAR" },
      { label: "Аккумулятор", value: "4276 мА·ч, 14.76 В" },
      { label: "Передача видео", value: "DJI O4+, до 20 км" },
      { label: "Внутренняя память", value: "42 ГБ + microSD до 1 ТБ" },
      { label: "ActiveTrack", value: "ActiveTrack 360°" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "drones-9",
    slug: "dji-avata-360",
    name: "DJI Avata 360",
    brand: "DJI",
    category: "drones",
    badge: "360",
    priceBYN: 9231,
    shortDescription: "DJI Avata 360 для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "DJI Avata 360 для аэросъемки и сложных условий. Стабильный полет и точная навигация. Компактный FPV-дрон со сферической камерой 8K снимает сразу всё пространство вокруг — после полёта вы кадрируете нужный ракурс в любую сторону. Защитные кожухи пропеллеров, RTH и стабилизация RockSteady 4.0 позволяют использовать его в закрытых пространствах и при сложных пролётах сквозь препятствия.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "360° сферическая, 8K" },
      { icon: "flight", label: "Полёт", value: "до 23 минут" },
      { icon: "distance", label: "Дистанция", value: "DJI O4, до 13 км" },
      { icon: "video", label: "Видео", value: "до 200 Мбит/с" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "498 г" },
      { label: "Размеры", value: "180 × 180 × 80 мм" },
      { label: "Максимальная скорость", value: "27 м/с" },
      { label: "Камера", value: "Двойная 1/2\" CMOS, FOV 360°" },
      { label: "Фото", value: "120 МП панорама" },
      { label: "Видео", value: "8K при 30 к/с, 5.7K при 60 к/с" },
      { label: "Стабилизация", value: "RockSteady 4.0, HorizonSteady" },
      { label: "Битрейт", value: "до 200 Мбит/с, H.265" },
      { label: "Цветовой профиль", value: "D-Log M, HLG, Normal" },
      { label: "Аккумулятор", value: "2150 мА·ч, 14.76 В" },
      { label: "Полётное время", value: "до 23 минут" },
      { label: "Передача видео", value: "DJI O4, до 13 км" },
      { label: "Защита пропеллеров", value: "Полная (защитные кольца)" },
      { label: "Совместимость очков", value: "DJI Goggles N3 / Integra" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "drones-10",
    slug: "dji-mavic-3",
    name: "DJI Mavic 3",
    brand: "DJI",
    category: "drones",
    badge: "PRO",
    priceBYN: 18933,
    shortDescription: "DJI Mavic 3 для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "DJI Mavic 3 для аэросъемки и сложных условий. Стабильный полет и точная навигация. Двойная камера Hasselblad совмещает 4/3 CMOS-сенсор с цветопередачей HNCS и теле-камеру 28× для съёмки на удалении. Профиль D-Log в 10-битах открывает простор для пост-обработки, а 46-минутное время полёта и передача O3+ на 15 км делают Mavic 3 эталоном среди дронов потребительского класса.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "4/3 Hasselblad CMOS, 20 МП" },
      { icon: "flight", label: "Полёт", value: "до 46 минут" },
      { icon: "distance", label: "Дистанция", value: "—" },
      { icon: "video", label: "Видео", value: "5.1K · 50 к/с, 10-bit D-Log" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "895 г" },
      { label: "Размеры", value: "347 × 283 × 107 мм" },
      { label: "Максимальная скорость", value: "21 м/с" },
      { label: "Защита от ветра", value: "до 12 м/с" },
      { label: "Основная камера", value: "4/3 CMOS Hasselblad, 20 МП" },
      { label: "Теле-камера", value: "1/2\" CMOS, 162 мм, f/4.4" },
      { label: "Видео", value: "5.1K при 50 к/с, 4K при 120 к/с" },
      { label: "Цветовой профиль", value: "10-bit D-Log, HNCS" },
      { label: "Битрейт", value: "до 200 Мбит/с, H.265" },
      { label: "Обход препятствий", value: "Всенаправленный APAS 5.0" },
      { label: "Аккумулятор", value: "5000 мА·ч, 17.6 В" },
      { label: "Полётное время", value: "до 46 минут" },
      { label: "Передача видео", value: "DJI O3+, до 15 км" },
      { label: "Внутренняя память", value: "8 ГБ + microSD до 2 ТБ" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "drones-11",
    slug: "dji-mini-4-pro",
    name: "DJI Mini 4 Pro",
    brand: "DJI",
    category: "drones",
    badge: "PRO",
    priceBYN: 7013,
    shortDescription: "DJI Mini 4 Pro для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "DJI Mini 4 Pro для аэросъемки и сложных условий. Стабильный полет и точная навигация. Самый лёгкий профессиональный дрон DJI весом до 249 г не требует регистрации во многих странах и при этом снимает 4K HDR с частотой 100 к/с и 10-битным D-Log M. ActiveTrack 360°, всенаправленное обнаружение препятствий и канал O4 на 20 км превращают компактный квадрокоптер в полноценный творческий инструмент.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "1/1.3\" CMOS, 48 МП" },
      { icon: "flight", label: "Полёт", value: "до 34 минут (45 с Plus)" },
      { icon: "distance", label: "Дистанция", value: "до 20 км (O4)" },
      { icon: "video", label: "Видео", value: "4K HDR · 100 к/с" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "<249 г" },
      { label: "Размеры", value: "298 × 373 × 101 мм" },
      { label: "Максимальная скорость", value: "16 м/с" },
      { label: "Камера", value: "1/1.3\" CMOS, 48 МП" },
      { label: "Объектив", value: "24 мм, f/1.7" },
      { label: "Фото", value: "48 МП, RAW (DNG)" },
      { label: "Видео", value: "4K при 100 к/с, 10-bit D-Log M" },
      { label: "Цветовой профиль", value: "Normal, HLG, D-Log M" },
      { label: "Обход препятствий", value: "Всенаправленный" },
      { label: "ActiveTrack", value: "ActiveTrack 360°" },
      { label: "Аккумулятор", value: "2590 мА·ч (стандарт)" },
      { label: "Полётное время", value: "34 / 45 минут (Plus)" },
      { label: "Передача видео", value: "DJI O4, до 20 км" },
      { label: "Внутренняя память", value: "Только microSD до 512 ГБ" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "drones-12",
    slug: "dji-neo-2",
    name: "DJI Neo 2",
    brand: "DJI",
    category: "drones",
    badge: "NEW",
    priceBYN: 3225,
    shortDescription: "DJI Neo 2 для аэросъемки и сложных условий. Стабильный полет и точная навигация.",
    longDescription:
      "DJI Neo 2 для аэросъемки и сложных условий. Стабильный полет и точная навигация. Сверхлёгкий дрон-селфи весом 135 г взлетает с ладони и снимает 4K-видео с интеллектуальной стабилизацией. Шесть автоматических режимов съёмки — Follow, Orbit, Spotlight и другие — работают без пульта и пилота, а голосовое управление позволяет управлять полётом без дополнительных аксессуаров.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "4K · 30 к/с" },
      { icon: "flight", label: "Полёт", value: "до 18 минут" },
      { icon: "distance", label: "Вес", value: "135 г" },
      { icon: "video", label: "Видео", value: "Жесты / голос / приложение" },
    ],
    techSpecs: [
      { label: "Взлётная масса", value: "135 г" },
      { label: "Размеры", value: "130 × 157 × 48 мм" },
      { label: "Максимальная скорость", value: "10 м/с" },
      { label: "Камера", value: "1/2\" CMOS, 12 МП" },
      { label: "Объектив", value: "f/2.4, FOV 117°" },
      { label: "Фото", value: "12 МП JPEG" },
      { label: "Видео", value: "4K при 30 к/с, 1080p при 60 к/с" },
      { label: "Стабилизация", value: "RockSteady + HorizonBalancing" },
      { label: "Полётное время", value: "до 18 минут" },
      { label: "Защита пропеллеров", value: "Встроенная (полная)" },
      { label: "Управление без пульта", value: "Голос / Жесты / App" },
      { label: "AI-режимы", value: "Follow, Orbit, Spotlight, DroneE" },
      { label: "Аккумулятор", value: "1435 мА·ч, 7.7 В" },
      { label: "Внутренняя память", value: "22 ГБ" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },

  {
    id: "cameras-1",
    slug: "dji-osmo-360",
    name: "DJI Osmo 360",
    brand: "DJI",
    category: "cameras",
    badge: "360",
    priceBYN: 4611,
    shortDescription: "DJI Osmo 360 для динамичного контента и путешествий. Четкое видео и надежная стабилизация.",
    longDescription:
      "DJI Osmo 360 для динамичного контента и путешествий. Четкое видео и надежная стабилизация. Сферическая камера снимает 8K-видео с глубокой постобработкой ракурса — выбирайте кадр уже после поездки. Двойные сенсоры 1/1.7\" с HDR, защита от воды на глубине 10 м и магнитное крепление совместимы с большинством аксессуаров Osmo.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "Двойной 1/1.7\" CMOS" },
      { icon: "flight", label: "Запись", value: "до 100 минут 5.7K" },
      { icon: "distance", label: "Защита", value: "до 10 м (водонепроницаемость)" },
      { icon: "video", label: "Видео", value: "8K · 30 к/с (360°)" },
    ],
    techSpecs: [
      { label: "Размеры", value: "73 × 50 × 38 мм" },
      { label: "Масса", value: "183 г" },
      { label: "Сенсоры", value: "Двойные 1/1.7\" CMOS, f/1.9" },
      { label: "Фото", value: "120 МП панорама, 18 МП плоское" },
      { label: "Видео 360", value: "8K при 30 к/с, 5.7K при 60 к/с" },
      { label: "Видео плоское", value: "4K при 60 к/с" },
      { label: "Битрейт", value: "до 130 Мбит/с (H.265)" },
      { label: "Стабилизация", value: "HorizonSteady, RockSteady 3.0" },
      { label: "Цветовой профиль", value: "D-Log M, HLG, Normal" },
      { label: "Защита", value: "Водонепроницаемость 10 м без бокса" },
      { label: "Микрофоны", value: "4 стерео, DJI Mic 2 BT" },
      { label: "Аккумулятор", value: "1950 мА·ч" },
      { label: "Время записи", value: "до 100 минут 5.7K" },
      { label: "Подключение", value: "USB-C, Wi-Fi 6, Bluetooth 5.2" },
      { label: "Хранение", value: "microSD до 1 ТБ" },
    ],
  },
  {
    id: "cameras-2",
    slug: "dji-osmo-action-5-pro-standard-combo",
    name: "DJI Osmo Action 5 Pro Standard Combo",
    brand: "DJI",
    category: "cameras",
    badge: "PRO",
    priceBYN: 3225,
    shortDescription:
      "DJI Osmo Action 5 Pro Standard Combo для динамичного контента и путешествий. Четкое видео и надежная стабилизация.",
    longDescription:
      "DJI Osmo Action 5 Pro Standard Combo для динамичного контента и путешествий. Четкое видео и надежная стабилизация. Сенсор 1/1.3\" с динамическим диапазоном 13.5 ступеней пишет 4K/120 с цветовым профилем D-Log M, а водозащита до 20 м без бокса позволяет снимать сразу из коробки. В комплект входят расширенный аккумулятор, рамка-адаптер и магнитное крепление.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "1/1.3\" CMOS" },
      { icon: "flight", label: "Полёт", value: "13.5 ступеней" },
      { icon: "distance", label: "Дистанция", value: "до 20 м без бокса" },
      { icon: "video", label: "Видео", value: "4K · 120 к/с" },
    ],
    techSpecs: [
      { label: "Размеры", value: "70.5 × 44.2 × 32.8 мм" },
      { label: "Масса", value: "146 г" },
      { label: "Сенсор", value: "1/1.3\" CMOS" },
      { label: "Объектив", value: "f/2.8, FOV 155°" },
      { label: "Видео", value: "4K при 120 к/с, 2.7K при 240 к/с" },
      { label: "Битрейт", value: "до 130 Мбит/с (H.265)" },
      { label: "Цветовой профиль", value: "D-Log M, HLG, Normal" },
      { label: "Стабилизация", value: "RockSteady 3.0+, HorizonSteady" },
      { label: "Фото", value: "40 МП JPEG/RAW" },
      { label: "Защита", value: "Водонепроницаемость до 20 м" },
      { label: "Микрофоны", value: "3 встроенных + DJI Mic 2 BT" },
      { label: "Сенсорный экран", value: "Двойные OLED, 1\" + 2.5\"" },
      { label: "Аккумулятор", value: "1950 мА·ч (Extreme)" },
      { label: "Время записи", value: "до 4 ч 4K/30" },
      { label: "Подключение", value: "USB-C, Wi-Fi 6, BT 5.2" },
    ],
  },
  {
    id: "cameras-3",
    slug: "dji-osmo-nano-standard-combo",
    name: "DJI Osmo Nano Standard Combo",
    brand: "DJI",
    category: "cameras",
    badge: "NEW",
    priceBYN: 1839,
    shortDescription:
      "DJI Osmo Nano Standard Combo для динамичного контента и путешествий. Четкое видео и надежная стабилизация.",
    longDescription:
      "DJI Osmo Nano Standard Combo для динамичного контента и путешествий. Четкое видео и надежная стабилизация. Миниатюрная экшн-камера весом 52 г крепится магнитом на одежду или шлем и пишет 4K/60 в режиме hands-free. Модуль-видоискатель отсоединяется и подключается по Wi-Fi, чтобы видеть кадр в реальном времени.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "52 г" },
      { icon: "flight", label: "Полёт", value: "Магнитное" },
      { icon: "distance", label: "Дистанция", value: "Съёмный по Wi-Fi" },
      { icon: "video", label: "Видео", value: "4K · 60 к/с" },
    ],
    techSpecs: [
      { label: "Размеры", value: "57 × 29 × 28 мм" },
      { label: "Масса", value: "52 г" },
      { label: "Сенсор", value: "1/1.3\" CMOS" },
      { label: "Объектив", value: "f/2.4, FOV 143°" },
      { label: "Видео", value: "4K при 60 к/с, 2.7K при 120 к/с" },
      { label: "Фото", value: "12 МП JPEG/RAW" },
      { label: "Стабилизация", value: "RockSteady, HorizonBalancing" },
      { label: "Микрофоны", value: "2 стерео, DJI Mic BT" },
      { label: "Защита", value: "IP68, до 10 м" },
      { label: "Видоискатель", value: "Внешний OLED 2.5\"" },
      { label: "Связь видоискатель–камера", value: "Wi-Fi 6, до 50 м" },
      { label: "Аккумулятор", value: "530 мА·ч (камера) + 1200 (видоиск.)" },
      { label: "Время записи", value: "до 90 минут 4K/30" },
      { label: "Подключение", value: "USB-C, Wi-Fi 6, BT 5.2" },
      { label: "Хранение", value: "32 ГБ встроенной + microSD" },
    ],
  },
  {
    id: "cameras-4",
    slug: "dji-osmo-pocket-3",
    name: "DJI Osmo Pocket 3",
    brand: "DJI",
    category: "cameras",
    badge: "PRO",
    priceBYN: 4796,
    shortDescription:
      "DJI Osmo Pocket 3 для динамичного контента и путешествий. Четкое видео и надежная стабилизация.",
    longDescription:
      "DJI Osmo Pocket 3 для динамичного контента и путешествий. Четкое видео и надежная стабилизация. Карманная камера с 1-дюймовым сенсором, моторизированным трёхосевым стабилизатором и поворотным OLED-экраном 2 дюйма позволяет сразу переключаться между горизонтальной и вертикальной съёмкой. ActiveTrack 6.0 удерживает объект в кадре, а D-Log M в 10 битах открывает кинематографические оттенки.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "1\" CMOS" },
      { icon: "flight", label: "Запись", value: "до 116 минут 4K/30" },
      { icon: "distance", label: "Экран", value: "2\" OLED, поворотный" },
      { icon: "video", label: "Видео", value: "4K · 120 к/с, 10-bit D-Log M" },
    ],
    techSpecs: [
      { label: "Размеры", value: "139.7 × 42.2 × 33.5 мм" },
      { label: "Масса", value: "179 г" },
      { label: "Сенсор", value: "1\" CMOS" },
      { label: "Объектив", value: "20 мм, f/2.0" },
      { label: "Видео", value: "4K при 120 к/с, FHD при 240 к/с" },
      { label: "Цветовой профиль", value: "10-bit D-Log M, HLG, Normal" },
      { label: "Гимбал", value: "3-осевой механический" },
      { label: "Фото", value: "9.4 МП JPEG/RAW" },
      { label: "Фокусировка", value: "Гибридная PDAF, ActiveTrack 6.0" },
      { label: "Экран", value: "2\" OLED, ёмкостный, поворот 90°" },
      { label: "Микрофоны", value: "4 встроенных + DJI Mic 2 BT" },
      { label: "Аккумулятор", value: "1300 мА·ч" },
      { label: "Время записи", value: "до 116 минут 4K/30" },
      { label: "Подключение", value: "USB-C, Wi-Fi 6, BT 5.2" },
      { label: "Хранение", value: "microSD до 512 ГБ" },
    ],
  },
  {
    id: "cameras-5",
    slug: "gopro-hero-13-black-ultra-wide-edition",
    name: "GoPro Hero 13 Black Ultra Wide Edition",
    brand: "GoPro",
    category: "cameras",
    badge: "PRO",
    priceBYN: 4149,
    shortDescription:
      "GoPro Hero 13 Black Ultra Wide Edition для динамичного контента и путешествий. Четкое видео и надежная стабилизация.",
    longDescription:
      "GoPro Hero 13 Black Ultra Wide Edition для динамичного контента и путешествий. Четкое видео и надежная стабилизация. Версия Ultra Wide включает фирменный объектив Ultra Wide Mod с FOV 177°, идеальным для скейтбординга, серфинга и POV-съёмки. Сенсор 1/1.9\" пишет 5.3K/60 с HyperSmooth 6.0, а аккумулятор Enduro работает на холоде без потери ёмкости.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "1/1.9\" CMOS" },
      { icon: "flight", label: "Полёт", value: "HyperSmooth 6.0" },
      { icon: "distance", label: "Дистанция", value: "—" },
      { icon: "video", label: "Видео", value: "5.3K · 60 к/с" },
    ],
    techSpecs: [
      { label: "Размеры", value: "71 × 50.8 × 33.6 мм" },
      { label: "Масса", value: "159 г" },
      { label: "Сенсор", value: "1/1.9\" CMOS" },
      { label: "Объектив (комплект)", value: "Ultra Wide Mod 2.0, FOV 177°" },
      { label: "Видео", value: "5.3K при 60 к/с, 4K при 120 к/с" },
      { label: "Битрейт", value: "до 120 Мбит/с (H.265)" },
      { label: "Фото", value: "27 МП JPEG/RAW" },
      { label: "Цветовой профиль", value: "GP-Log, HLG, Natural" },
      { label: "Стабилизация", value: "HyperSmooth 6.0, Horizon Lock" },
      { label: "Защита", value: "Водонепроницаемость до 10 м" },
      { label: "Сенсорный экран", value: "Задний 2.27\" + передний 1.4\"" },
      { label: "Микрофоны", value: "3, с шумоподавлением" },
      { label: "Аккумулятор", value: "Enduro 1900 мА·ч" },
      { label: "Подключение", value: "USB-C, Wi-Fi 6, BT 5.0" },
      { label: "Хранение", value: "microSD до 1 ТБ" },
    ],
  },
  {
    id: "cameras-6",
    slug: "gopro-hero-13",
    name: "GoPro Hero 13",
    brand: "GoPro",
    category: "cameras",
    badge: "NEW",
    priceBYN: 3687,
    shortDescription:
      "GoPro Hero 13 для динамичного контента и путешествий. Четкое видео и надежная стабилизация.",
    longDescription:
      "GoPro Hero 13 для динамичного контента и путешествий. Четкое видео и надежная стабилизация. Тринадцатое поколение Hero получило обновлённый процессор GP3 и систему сменных объективов HB-Series, что даёт творческую свободу при той же легендарной прочности корпуса. 5.3K/60, передовое шумоподавление и LiveBurst делают серию универсальным выбором для блогеров и спортсменов.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "1/1.9\" CMOS" },
      { icon: "flight", label: "Полёт", value: "HyperSmooth 6.0" },
      { icon: "distance", label: "Дистанция", value: "—" },
      { icon: "video", label: "Видео", value: "5.3K · 60 к/с" },
    ],
    techSpecs: [
      { label: "Размеры", value: "71 × 50.8 × 33.6 мм" },
      { label: "Масса", value: "154 г" },
      { label: "Сенсор", value: "1/1.9\" CMOS" },
      { label: "Объектив", value: "f/2.5, FOV 156° (Wide)" },
      { label: "Сменные модули", value: "HB-Series Ultra Wide, Macro, ND" },
      { label: "Видео", value: "5.3K при 60 к/с, 4K при 120 к/с" },
      { label: "Битрейт", value: "до 120 Мбит/с (H.265)" },
      { label: "Фото", value: "27 МП, RAW (GPR/DNG)" },
      { label: "Стабилизация", value: "HyperSmooth 6.0, AutoBoost" },
      { label: "Защита", value: "Водонепроницаемость до 10 м" },
      { label: "Сенсорный экран", value: "2.27\" задний + 1.4\" передний" },
      { label: "Микрофоны", value: "3 встроенных с шумоподавлением" },
      { label: "Аккумулятор", value: "Enduro 1900 мА·ч" },
      { label: "Подключение", value: "USB-C, Wi-Fi 6, BT 5.0" },
      { label: "Хранение", value: "microSD до 1 ТБ" },
    ],
  },
  {
    id: "cameras-7",
    slug: "gopro-hero",
    name: "GoPro Hero",
    brand: "GoPro",
    category: "cameras",
    badge: "NEW",
    priceBYN: 2763,
    shortDescription:
      "GoPro Hero для динамичного контента и путешествий. Четкое видео и надежная стабилизация.",
    longDescription:
      "GoPro Hero для динамичного контента и путешествий. Четкое видео и надежная стабилизация. Лёгкая (86 г) и компактная экшн-камера для повседневной съёмки: 4K/30, HyperSmooth, защита от воды до 5 м и простое управление одной кнопкой делают её идеальной для тех, кто только начинает свой путь в видеосъёмке.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "86 г" },
      { icon: "flight", label: "Полёт", value: "HyperSmooth" },
      { icon: "distance", label: "Дистанция", value: "Водонепроницаемость до 5 м" },
      { icon: "video", label: "Видео", value: "4K · 30 к/с" },
    ],
    techSpecs: [
      { label: "Размеры", value: "56.2 × 47.8 × 29.2 мм" },
      { label: "Масса", value: "86 г" },
      { label: "Сенсор", value: "1/2.3\" CMOS" },
      { label: "Объектив", value: "f/2.8, FOV 156°" },
      { label: "Видео", value: "4K при 30 к/с, 2.7K при 60 к/с" },
      { label: "Битрейт", value: "до 100 Мбит/с (H.265)" },
      { label: "Фото", value: "12 МП JPEG" },
      { label: "Стабилизация", value: "HyperSmooth" },
      { label: "Защита", value: "Водонепроницаемость до 5 м" },
      { label: "Сенсорный экран", value: "1.76\" задний" },
      { label: "Микрофоны", value: "2 встроенных" },
      { label: "Аккумулятор", value: "1500 мА·ч, несъёмный" },
      { label: "Подключение", value: "USB-C, Wi-Fi" },
      { label: "Хранение", value: "microSD до 512 ГБ" },
      { label: "Рабочая температура", value: "−10 ... +35 °C" },
    ],
  },
  {
    id: "cameras-8",
    slug: "gopro-max",
    name: "GoPro MAX",
    brand: "GoPro",
    category: "cameras",
    badge: "MAX",
    priceBYN: 3687,
    shortDescription:
      "GoPro MAX для динамичного контента и путешествий. Четкое видео и надежная стабилизация.",
    longDescription:
      "GoPro MAX для динамичного контента и путешествий. Четкое видео и надежная стабилизация. 360-камера с двумя объективами, передовой стабилизацией Max HyperSmooth и шестью микрофонами для пространственного звука. Перекадрирование без потери качества помогает создавать кинематографичные ролики уже в смартфоне.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "5.6K · 30 к/с" },
      { icon: "flight", label: "Полёт", value: "Max HyperSmooth" },
      { icon: "distance", label: "Дистанция", value: "Водонепроницаемость до 5 м" },
      { icon: "video", label: "Видео", value: "6 встроенных" },
    ],
    techSpecs: [
      { label: "Размеры", value: "64 × 69 × 25 мм" },
      { label: "Масса", value: "163 г" },
      { label: "Сенсоры", value: "Двойные 1/2.3\" CMOS" },
      { label: "Объективы", value: "Двойные f/2.8" },
      { label: "Видео 360", value: "5.6K при 30 к/с" },
      { label: "Видео Hero", value: "1440p при 60 к/с" },
      { label: "Фото", value: "16.6 МП (PowerPano)" },
      { label: "Стабилизация", value: "Max HyperSmooth, Horizon Leveling" },
      { label: "Звук", value: "6 микрофонов, 360° Audio" },
      { label: "Защита", value: "Водонепроницаемость до 5 м" },
      { label: "Сенсорный экран", value: "Задний 1.74\"" },
      { label: "Аккумулятор", value: "1600 мА·ч" },
      { label: "Подключение", value: "USB-C, Wi-Fi, BT" },
      { label: "Хранение", value: "microSD до 256 ГБ" },
      { label: "Рабочая температура", value: "−10 ... +35 °C" },
    ],
  },
  {
    id: "cameras-9",
    slug: "gopro-max2",
    name: "GoPro MAX2",
    brand: "GoPro",
    category: "cameras",
    badge: "MAX",
    priceBYN: 4611,
    shortDescription:
      "GoPro MAX2 для динамичного контента и путешествий. Четкое видео и надежная стабилизация.",
    longDescription:
      "GoPro MAX2 для динамичного контента и путешествий. Четкое видео и надежная стабилизация. Преемник GoPro MAX получил обновлённые сенсоры 1/1.7\", запись 8K-видео в 360°, поддержку 10-битного цвета и сменные защитные стёкла. Mod-крепления и совместимость с DJI Mic 2 делают камеру выбором для блогеров и операторов.",
    briefSpecs: [
      { icon: "camera", label: "Камера", value: "8K · 30 к/с, 360°" },
      { icon: "flight", label: "Профиль", value: "10-bit, GP-Log" },
      { icon: "distance", label: "Микрофоны", value: "8 направленных" },
      { icon: "video", label: "Видео", value: "Водонепроницаемость до 10 м" },
    ],
    techSpecs: [
      { label: "Размеры", value: "70 × 73 × 28 мм" },
      { label: "Масса", value: "192 г" },
      { label: "Сенсоры", value: "Двойные 1/1.7\" CMOS" },
      { label: "Объективы", value: "Сменные защитные стёкла" },
      { label: "Видео 360", value: "8K при 30 к/с, 5.7K при 60 к/с" },
      { label: "Видео Hero", value: "4K при 60 к/с" },
      { label: "Битрейт", value: "до 150 Мбит/с" },
      { label: "Цветовой профиль", value: "10-bit, GP-Log, HLG" },
      { label: "Фото", value: "29.6 МП PowerPano" },
      { label: "Стабилизация", value: "Max HyperSmooth 2.0" },
      { label: "Звук", value: "8 микрофонов, Spatial Audio" },
      { label: "Защита", value: "Водонепроницаемость до 10 м" },
      { label: "Аккумулятор", value: "Enduro 1900 мА·ч" },
      { label: "Подключение", value: "USB-C, Wi-Fi 6, BT 5.0" },
      { label: "Хранение", value: "microSD до 1 ТБ" },
    ],
  },

  {
    id: "accessories-1",
    slug: "autel-controller",
    name: "Autel Controller",
    brand: "Autel",
    category: "accessories",
    badge: "CONTROL",
    priceBYN: 11550,
    shortDescription:
      "Autel Controller расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "Autel Controller расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Профессиональный пульт со встроенным дисплеем 7.9\" 2000 нит, поддержкой DRTK-передачи на 20 км и шифрованием AES-256. Подходит для всей линейки Autel EVO и Alpha — снимайте на ярком солнце и работайте с миссиями прямо из меню пульта.",
    briefSpecs: [
      { icon: "camera", label: "Дисплей", value: "7.9\" 2000 нит" },
      { icon: "flight", label: "Совместимость", value: "EVO / Alpha серии" },
      { icon: "distance", label: "Связь", value: "Autel DRTK, до 20 км" },
      { icon: "video", label: "Шифрование", value: "AES-256" },
    ],
    techSpecs: [
      { label: "Дисплей", value: "7.9\" IPS, 2000 нит, 1920×1200" },
      { label: "Сенсорный экран", value: "Мультитач 10-точечный" },
      { label: "Передача видео", value: "Autel DRTK, до 20 км" },
      { label: "Шифрование", value: "AES-256, end-to-end" },
      { label: "Совместимость", value: "EVO II / EVO Max / Alpha" },
      { label: "Аккумулятор", value: "10000 мА·ч (несъёмный)" },
      { label: "Время работы", value: "до 4.5 часов" },
      { label: "Зарядка", value: "USB-C PD, 65 Вт" },
      { label: "GNSS", value: "GPS, GLONASS, Galileo" },
      { label: "Wi-Fi", value: "Wi-Fi 6 (802.11ax)" },
      { label: "Bluetooth", value: "5.2" },
      { label: "Порты", value: "USB-C, HDMI, microSD" },
      { label: "Защита", value: "IP43" },
      { label: "Рабочая температура", value: "−20 ... +50 °C" },
      { label: "Масса", value: "1240 г" },
    ],
  },
  {
    id: "accessories-2",
    slug: "autel-power-hub",
    name: "Autel Power Hub",
    brand: "Autel",
    category: "accessories",
    badge: "NEW",
    priceBYN: 1746,
    shortDescription:
      "Autel Power Hub расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "Autel Power Hub расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Зарядная станция одновременно подключает до четырёх аккумуляторов EVO 2 / EVO Lite и распределяет мощность 240 Вт. Поддержка быстрой зарядки, индикаторы состояния и режим хранения сохраняют ресурс батарей в долгих экспедициях.",
    briefSpecs: [
      { icon: "camera", label: "Слоты", value: "4 аккумулятора" },
      { icon: "flight", label: "Мощность", value: "240 Вт" },
      { icon: "distance", label: "Совместимость", value: "EVO 2 / EVO Lite" },
      { icon: "video", label: "Режим", value: "Зарядка / хранение" },
    ],
    techSpecs: [
      { label: "Мощность", value: "240 Вт (60 Вт / канал)" },
      { label: "Каналов", value: "4 одновременно" },
      { label: "Вход", value: "100–240 В, 50/60 Гц" },
      { label: "Совместимость", value: "EVO 2 / EVO Lite / EVO 2 Pro" },
      { label: "Время зарядки", value: "~70 минут до 100% (одна АКБ)" },
      { label: "Режимы", value: "Быстрая зарядка / Хранение" },
      { label: "Индикация", value: "LED-индикаторы статуса" },
      { label: "Защита", value: "От перенапряжения, перегрева, КЗ" },
      { label: "Порты", value: "USB-A для пульта/телефона" },
      { label: "Размеры", value: "260 × 180 × 70 мм" },
      { label: "Масса", value: "780 г" },
      { label: "Рабочая температура", value: "5 ... +40 °C" },
    ],
  },
  {
    id: "accessories-3",
    slug: "dji-65w-car-charger",
    name: "DJI 65W Car Charger",
    brand: "DJI",
    category: "accessories",
    badge: "NEW",
    priceBYN: 453,
    shortDescription:
      "DJI 65W Car Charger расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI 65W Car Charger расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Автомобильное зарядное устройство 65 Вт с двумя портами USB-C и поддержкой Power Delivery 3.0 заряжает аккумуляторы Mavic 3, Air 3 и Mini 4 Pro прямо в пути. Технология SmartShare распределяет мощность между подключёнными устройствами.",
    briefSpecs: [
      { icon: "camera", label: "Мощность", value: "65 Вт PD 3.0" },
      { icon: "flight", label: "Порты", value: "2 × USB-C" },
      { icon: "distance", label: "Вход", value: "12–24 В DC" },
      { icon: "video", label: "Совместимость", value: "Mavic 3 / Air 3 / Mini 4 Pro" },
    ],
    techSpecs: [
      { label: "Мощность", value: "65 Вт (PD 3.0)" },
      { label: "Порты", value: "USB-C × 2" },
      { label: "Вход", value: "12–24 В DC, 8 А макс" },
      { label: "Технология распределения", value: "DJI SmartShare" },
      { label: "Совместимость", value: "Mavic 3 / Air 3 / Mini 4 Pro / RC 2" },
      { label: "Длина кабеля", value: "1.0 м (USB-C – USB-C)" },
      { label: "Защита", value: "Перенапряжение, перегрев, КЗ" },
      { label: "Корпус", value: "Алюминий + ABS" },
      { label: "Размеры", value: "75 × 27 × 27 мм" },
      { label: "Масса", value: "52 г" },
      { label: "Сертификация", value: "CE, FCC, RoHS" },
    ],
  },
  {
    id: "accessories-4",
    slug: "dji-avata-2-intelligent-flight-battery",
    name: "DJI Avata 2 Intelligent Flight Battery",
    brand: "DJI",
    category: "accessories",
    badge: "АКБ",
    priceBYN: 1192,
    shortDescription:
      "DJI Avata 2 Intelligent Flight Battery расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI Avata 2 Intelligent Flight Battery расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Интеллектуальный аккумулятор LiPo 4S повышает полётное время Avata 2 до 23 минут и поддерживает быструю зарядку 1.5 А. Встроенная защита от глубокого разряда, переполюсовки и перегрева делает АКБ полностью безопасной для активной FPV-съёмки.",
    briefSpecs: [
      { icon: "camera", label: "Тип", value: "LiPo 4S" },
      { icon: "flight", label: "Ёмкость", value: "2150 мА·ч" },
      { icon: "distance", label: "Зарядка", value: "USB-C PD 30 Вт" },
      { icon: "video", label: "Полёт", value: "до 23 минут (Avata 2)" },
    ],
    techSpecs: [
      { label: "Тип", value: "LiPo 4S" },
      { label: "Ёмкость", value: "2150 мА·ч" },
      { label: "Энергия", value: "31.7 Вт·ч" },
      { label: "Напряжение", value: "14.76 В" },
      { label: "Зарядка", value: "USB-C PD 30 Вт" },
      { label: "Время зарядки", value: "~45 минут до 100%" },
      { label: "Полётное время", value: "до 23 минут (Avata 2)" },
      { label: "Совместимость", value: "DJI Avata 2" },
      { label: "BMS", value: "Защита от КЗ, переразряда, перегрева" },
      { label: "Масса", value: "175 г" },
      { label: "Размеры", value: "94 × 49 × 27 мм" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "accessories-5",
    slug: "dji-avata-2-propellers",
    name: "DJI Avata 2 Propellers",
    brand: "DJI",
    category: "accessories",
    badge: "NEW",
    priceBYN: 176,
    shortDescription:
      "DJI Avata 2 Propellers расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI Avata 2 Propellers расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Композитные пропеллеры с пониженным уровнем шума и улучшенным КПД увеличивают полётное время Avata 2 на 5%. В комплект входят четыре винта и набор стопорных колец — быстрая замена не требует инструмента.",
    briefSpecs: [
      { icon: "camera", label: "Состав", value: "4 шт. + кольца" },
      { icon: "flight", label: "Совместимость", value: "DJI Avata 2" },
      { icon: "distance", label: "Шум", value: "−2 дБ" },
      { icon: "video", label: "Материал", value: "Композит" },
    ],
    techSpecs: [
      { label: "Количество в наборе", value: "4 пропеллера + кольца" },
      { label: "Диаметр", value: "4 дюйма" },
      { label: "Материал", value: "Композитный пластик" },
      { label: "Совместимость", value: "DJI Avata 2" },
      { label: "Снижение шума", value: "до 2 дБ" },
      { label: "Эффективность", value: "+5% полётного времени" },
      { label: "Установка", value: "Без инструмента (твист-локк)" },
      { label: "Масса 1 шт.", value: "4.6 г" },
      { label: "Сертификация", value: "CE / FCC" },
    ],
  },
  {
    id: "accessories-6",
    slug: "dji-fpv-remote-controller-3",
    name: "DJI FPV Remote Controller 3",
    brand: "DJI",
    category: "accessories",
    badge: "CONTROL",
    priceBYN: 1839,
    shortDescription:
      "DJI FPV Remote Controller 3 расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI FPV Remote Controller 3 расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Эргономичный пульт с обновлёнными датчиками Холла и поддержкой O4-передачи рассчитан на FPV-полёты Avata 2 и FPV-системы DJI. Высокочастотный сэмплинг джойстиков, эргономика и автономность до 9 часов — для долгих сессий съёмок.",
    briefSpecs: [
      { icon: "camera", label: "Технология", value: "Датчики Холла, OcuSync 4" },
      { icon: "flight", label: "Автономность", value: "до 9 часов" },
      { icon: "distance", label: "Дальность", value: "до 13 км" },
      { icon: "video", label: "Совместимость", value: "Avata 2 / DJI FPV" },
    ],
    techSpecs: [
      { label: "Тип джойстиков", value: "Датчики Холла, съёмные стики" },
      { label: "Совместимость", value: "DJI Avata 2 / DJI FPV / Goggles N3" },
      { label: "Передача видео", value: "DJI O4, до 13 км" },
      { label: "Каналы", value: "2.4 / 5.1 / 5.8 ГГц" },
      { label: "Время работы", value: "до 9 часов" },
      { label: "Аккумулятор", value: "Несъёмный, 2600 мА·ч" },
      { label: "Зарядка", value: "USB-C PD" },
      { label: "Микроконтроллеры", value: "Высокочастотный опрос 1 кГц" },
      { label: "Эргономика", value: "Прорезиненные накладки" },
      { label: "Масса", value: "346 г" },
      { label: "Размеры", value: "190 × 140 × 51 мм" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "accessories-7",
    slug: "dji-goggles-n3",
    name: "DJI Goggles N3",
    brand: "DJI",
    category: "accessories",
    badge: "FPV",
    priceBYN: 4611,
    shortDescription:
      "DJI Goggles N3 расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI Goggles N3 расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. FPV-очки с одним крупным OLED-дисплеем, диоптрийной коррекцией и поддержкой OcuSync 4 показывают изображение в 1080p/100 при задержке всего 28 мс. Удобный размер, регулируемый межзрачковый интервал и Bluetooth-управление делают их универсальной заменой Goggles Integra.",
    briefSpecs: [
      { icon: "camera", label: "Дисплей", value: "Один OLED 1080p" },
      { icon: "flight", label: "Частота", value: "до 100 Гц" },
      { icon: "distance", label: "Задержка", value: "28 мс" },
      { icon: "video", label: "Связь", value: "DJI O4" },
    ],
    techSpecs: [
      { label: "Дисплей", value: "Один Micro-OLED, 1080p" },
      { label: "Частота обновления", value: "до 100 Гц" },
      { label: "FOV", value: "Эффективное 44°" },
      { label: "Задержка", value: "28 мс" },
      { label: "Передача", value: "DJI O4, до 13 км" },
      { label: "Совместимость", value: "DJI Avata 2 / DJI FPV / Neo 2" },
      { label: "Диоптрии", value: "Встроенная коррекция −8 до +2" },
      { label: "Межзрачковое расстояние", value: "56–72 мм" },
      { label: "Аудио", value: "Динамики + 3.5 мм" },
      { label: "Подключение", value: "USB-C, BT 5.2, HDMI вход" },
      { label: "Аккумулятор", value: "Внешний, 1800 мА·ч" },
      { label: "Время работы", value: "до 3.5 часов" },
      { label: "Масса", value: "395 г (без АКБ)" },
      { label: "Защита", value: "Сменные накладки, антибликовое покрытие" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "accessories-8",
    slug: "dji-inspire-3-foldable-propellers",
    name: "DJI Inspire 3 Foldable Quick-Release Propellers for High Altitude",
    brand: "DJI",
    category: "accessories",
    badge: "PRO",
    priceBYN: 2024,
    shortDescription:
      "DJI Inspire 3 Foldable Quick-Release Propellers for High Altitude расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI Inspire 3 Foldable Quick-Release Propellers for High Altitude расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Высокогорные пропеллеры специально рассчитаны для съёмок на высоте выше 2500 м. Увеличенный шаг и углепластиковый профиль обеспечивают стабильность Inspire 3 в разреженном воздухе и при максимальных динамических нагрузках.",
    briefSpecs: [
      { icon: "camera", label: "Состав", value: "4 шт. (CW + CCW)" },
      { icon: "flight", label: "Совместимость", value: "DJI Inspire 3" },
      { icon: "distance", label: "Высота", value: "до 5000 м" },
      { icon: "video", label: "Материал", value: "Углепластик" },
    ],
    techSpecs: [
      { label: "Количество в наборе", value: "4 пропеллера (2 пары)" },
      { label: "Совместимость", value: "DJI Inspire 3" },
      { label: "Тип", value: "Складные, Quick-Release" },
      { label: "Материал", value: "Углепластик + усиленный полимер" },
      { label: "Длина", value: "18 дюймов (457 мм)" },
      { label: "Рабочая высота", value: "до 5000 м над уровнем моря" },
      { label: "Снижение шума", value: "−3 дБ относительно стандартных" },
      { label: "Эффективность", value: "+8% подъёмной силы (3000 м)" },
      { label: "Установка", value: "Без инструмента" },
      { label: "Масса 1 шт.", value: "16.8 г" },
      { label: "Сертификация", value: "CE, FCC, RoHS" },
    ],
  },
  {
    id: "accessories-9",
    slug: "dji-inspire-3-gimbal-rubber-dampers",
    name: "DJI Inspire 3 Gimbal Rubber Dampers",
    brand: "DJI",
    category: "accessories",
    badge: "NEW",
    priceBYN: 268,
    shortDescription:
      "DJI Inspire 3 Gimbal Rubber Dampers расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI Inspire 3 Gimbal Rubber Dampers расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Сменные резиновые виброгасители для гимбала Inspire 3: снижают амплитуду микровибраций, повышая стабильность кадра при высоких скоростях. Набор включает шесть запасных колец и инструмент для установки.",
    briefSpecs: [
      { icon: "camera", label: "Состав", value: "6 шт. + установщик" },
      { icon: "flight", label: "Совместимость", value: "Inspire 3" },
      { icon: "distance", label: "Материал", value: "Резина TPU" },
      { icon: "video", label: "Гашение", value: "Микровибрации 200–800 Гц" },
    ],
    techSpecs: [
      { label: "Количество", value: "6 виброгасителей + установщик" },
      { label: "Совместимость", value: "DJI Inspire 3 / Zenmuse X9" },
      { label: "Материал", value: "TPU резина, твёрдость 60A" },
      { label: "Диапазон гашения", value: "200–800 Гц" },
      { label: "Условия эксплуатации", value: "−10 ... +40 °C" },
      { label: "Срок службы", value: "до 1000 циклов установки" },
      { label: "Замена", value: "Без снятия камеры" },
      { label: "Цвет", value: "Чёрный матовый" },
      { label: "Масса (комплект)", value: "12 г" },
    ],
  },
  {
    id: "accessories-10",
    slug: "dji-rc-n3-remote-controller",
    name: "DJI RC-N3 Remote Controller",
    brand: "DJI",
    category: "accessories",
    badge: "CONTROL",
    priceBYN: 1192,
    shortDescription:
      "DJI RC-N3 Remote Controller расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI RC-N3 Remote Controller расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Универсальный пульт без экрана с креплением для смартфона: подходит для Mavic 3 Pro, Air 3 и Mini 4 Pro. Поддерживает O4 на 20 км, USB-C-кабель для iOS и Android, складные джойстики и расширенный аккумулятор на 6 часов работы.",
    briefSpecs: [
      { icon: "camera", label: "Совместимость", value: "Mavic 3 / Air 3 / Mini 4 Pro" },
      { icon: "flight", label: "Крепление", value: "Под смартфон" },
      { icon: "distance", label: "Связь", value: "DJI O4, до 20 км" },
      { icon: "video", label: "Кабели", value: "USB-C / Lightning" },
    ],
    techSpecs: [
      { label: "Совместимость", value: "Mavic 3 / Air 3 / Mini 4 Pro" },
      { label: "Передача", value: "DJI O4, до 20 км (FCC)" },
      { label: "Частоты", value: "2.4 ГГц / 5.1 ГГц / 5.8 ГГц" },
      { label: "Тип джойстиков", value: "Складные, съёмные" },
      { label: "Крепление смартфона", value: "Универсальное (5\"–7\")" },
      { label: "Аккумулятор", value: "Несъёмный, 5200 мА·ч" },
      { label: "Время работы", value: "до 6 часов" },
      { label: "Зарядка", value: "USB-C PD" },
      { label: "Кабели в комплекте", value: "USB-C, Lightning, USB-A" },
      { label: "Масса", value: "365 г" },
      { label: "Размеры", value: "171 × 102 × 49 мм" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "accessories-11",
    slug: "dji-sdr-transmission-kit",
    name: "DJI SDR Transmission Kit",
    brand: "DJI",
    category: "accessories",
    badge: "PRO",
    priceBYN: 5073,
    shortDescription:
      "DJI SDR Transmission Kit расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI SDR Transmission Kit расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Беспроводная видеосистема с двойными антеннами обеспечивает передачу с задержкой 60 мс на расстояние до 6 км. Подходит для съёмочных команд кинопроизводства и работает с тремя приёмниками одновременно.",
    briefSpecs: [
      { icon: "camera", label: "Сигнал", value: "1080p/60" },
      { icon: "flight", label: "Задержка", value: "60 мс" },
      { icon: "distance", label: "Дальность", value: "до 6 км" },
      { icon: "video", label: "Приёмники", value: "до 3 одновременно" },
    ],
    techSpecs: [
      { label: "Передатчик", value: "Видео 1080p/60, до 80 Мбит/с" },
      { label: "Дальность", value: "до 6 км (LoS)" },
      { label: "Задержка", value: "60 мс" },
      { label: "Частоты", value: "2.4 / 5.1 / 5.8 ГГц, авто-хоп" },
      { label: "Приёмники", value: "До 3 одновременно" },
      { label: "Видео-входы", value: "SDI + HDMI" },
      { label: "Видео-выходы", value: "SDI + HDMI" },
      { label: "Питание", value: "DC-вход, V-mount, D-tap" },
      { label: "Мощность излучения", value: "до 1 Вт (EIRP)" },
      { label: "Размеры передатчика", value: "127 × 76 × 25 мм" },
      { label: "Масса (комплекта)", value: "640 г" },
      { label: "Шифрование", value: "AES-128" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },
  {
    id: "accessories-12",
    slug: "dji-sdr-transmission-receiver",
    name: "DJI SDR Transmission Receiver",
    brand: "DJI",
    category: "accessories",
    badge: "RX",
    priceBYN: 2024,
    shortDescription:
      "DJI SDR Transmission Receiver расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе.",
    longDescription:
      "DJI SDR Transmission Receiver расширяет возможности вашего комплекта. Надежная совместимость и удобство в работе. Дополнительный приёмник для расширения комплекта DJI SDR: позволяет добавить ещё одного оператора, режиссёра или фокус-пуллера. Поддерживает 1080p/60, питание V-mount и совместим с современными мониторами.",
    briefSpecs: [
      { icon: "camera", label: "Сигнал", value: "1080p/60" },
      { icon: "flight", label: "Задержка", value: "60 мс" },
      { icon: "distance", label: "Дальность", value: "до 6 км" },
      { icon: "video", label: "Выходы", value: "SDI / HDMI" },
    ],
    techSpecs: [
      { label: "Видео-выходы", value: "SDI + HDMI" },
      { label: "Видео-вход", value: "Беспроводной от SDR Transmitter" },
      { label: "Дальность", value: "до 6 км (LoS)" },
      { label: "Задержка", value: "60 мс" },
      { label: "Частоты", value: "2.4 / 5.1 / 5.8 ГГц" },
      { label: "Антенны", value: "Двойные, MIMO" },
      { label: "Питание", value: "DC, V-mount, NP-F970" },
      { label: "Потребление", value: "7 Вт" },
      { label: "Размеры", value: "121 × 71 × 24 мм" },
      { label: "Масса", value: "230 г" },
      { label: "Крепление", value: "1/4-20 + холодный башмак" },
      { label: "Шифрование", value: "AES-128" },
      { label: "Рабочая температура", value: "−10 ... +40 °C" },
    ],
  },

  {
    id: "microphones-1",
    slug: "dji-mic-2-transmitter",
    name: "DJI MIC 2 Transmitter",
    brand: "DJI",
    category: "microphones",
    badge: "AUDIO",
    priceBYN: 915,
    shortDescription:
      "DJI MIC 2 Transmitter для чистой речи и записи на выезде. Стабильный сигнал и компактный формат.",
    longDescription:
      "DJI MIC 2 Transmitter для чистой речи и записи на выезде. Стабильный сигнал и компактный формат. Беспроводной передатчик со встроенным шумоподавлением AI и 32-битной внутренней записью гарантирует студийный звук даже на улице. Магнитное крепление и кейс с автоматической зарядкой превращают подготовку к съёмке в дело двух секунд.",
    briefSpecs: [
      { icon: "camera", label: "Запись", value: "32-bit Float, внутр. 8 ГБ" },
      { icon: "flight", label: "Автономность", value: "до 6 часов" },
      { icon: "distance", label: "Дальность", value: "до 250 м" },
      { icon: "video", label: "Сигнал", value: "AI Adaptive" },
    ],
    techSpecs: [
      { label: "Тип", value: "Беспроводной передатчик" },
      { label: "Внутренняя запись", value: "32-bit Float, 8 ГБ" },
      { label: "Частотный диапазон", value: "20 Гц – 20 кГц" },
      { label: "Дальность передачи", value: "до 250 м (LoS)" },
      { label: "Шумоподавление", value: "AI Adaptive Noise Cancellation" },
      { label: "Частоты", value: "2.4 ГГц AFH" },
      { label: "Микрофон", value: "Встроенный + внешний 3.5 мм TRS" },
      { label: "Чувствительность", value: "−39 дБ" },
      { label: "Аккумулятор", value: "320 мА·ч" },
      { label: "Время работы", value: "до 6 часов" },
      { label: "Зарядка", value: "USB-C, ~1.5 ч полная" },
      { label: "Совместимость", value: "Mic 2 RX / Osmo Pocket 3 / Action 5" },
      { label: "Масса", value: "28 г" },
      { label: "Размеры", value: "44 × 30 × 16 мм" },
      { label: "Магнитное крепление", value: "Встроенное" },
    ],
  },
  {
    id: "microphones-2",
    slug: "dji-mic-mini-transmitter",
    name: "DJI Mic Mini Transmitter",
    brand: "DJI",
    category: "microphones",
    badge: "AUDIO",
    priceBYN: 545,
    shortDescription:
      "DJI Mic Mini Transmitter для чистой речи и записи на выезде. Стабильный сигнал и компактный формат.",
    longDescription:
      "DJI Mic Mini Transmitter для чистой речи и записи на выезде. Стабильный сигнал и компактный формат. Самый компактный передатчик DJI весом 10 г и автономностью 11.5 часов записывает чистую речь с дальностью 400 м. Магнитный клип и защита от ветра позволяют использовать его на пресс-конференциях, в путешествиях и для влогов.",
    briefSpecs: [
      { icon: "camera", label: "Запись", value: "10 г, ультракомпакт" },
      { icon: "flight", label: "Автономность", value: "до 11.5 часов" },
      { icon: "distance", label: "Дальность", value: "до 400 м" },
      { icon: "video", label: "Сигнал", value: "AI шумоподавление" },
    ],
    techSpecs: [
      { label: "Тип", value: "Беспроводной передатчик (мини)" },
      { label: "Масса", value: "10 г" },
      { label: "Размеры", value: "37 × 22 × 14 мм" },
      { label: "Частотный диапазон", value: "50 Гц – 20 кГц" },
      { label: "Шумоподавление", value: "AI Adaptive" },
      { label: "Дальность передачи", value: "до 400 м (LoS)" },
      { label: "Частоты", value: "2.4 ГГц AFH" },
      { label: "Аккумулятор", value: "180 мА·ч, несъёмный" },
      { label: "Время работы", value: "до 11.5 часов" },
      { label: "Зарядка", value: "USB-C, ~70 мин" },
      { label: "Кейс с зарядкой", value: "До 4 циклов передатчика" },
      { label: "Чувствительность", value: "−40 дБ" },
      { label: "Совместимость", value: "Mic 2 RX / Mic Mini RX" },
      { label: "Магнитное крепление", value: "Встроенное" },
      { label: "Защита от ветра", value: "Меховая ветрозащита в комплекте" },
    ],
  },
  {
    id: "microphones-3",
    slug: "dji-wireless-microphone-transmitter",
    name: "DJI Wireless Microphone Transmitter",
    brand: "DJI",
    category: "microphones",
    badge: "AUDIO",
    priceBYN: 822,
    shortDescription:
      "DJI Wireless Microphone Transmitter для чистой речи и записи на выезде. Стабильный сигнал и компактный формат.",
    longDescription:
      "DJI Wireless Microphone Transmitter для чистой речи и записи на выезде. Стабильный сигнал и компактный формат. Универсальный передатчик с прямым подключением к Osmo Action 5 Pro и Osmo Pocket 3 по Bluetooth: позволяет записывать студийный звук на саму камеру без отдельного приёмника. Внешний 3.5 мм вход, шумоподавление и автономность 6 часов перекроют любую съёмочную смену.",
    briefSpecs: [
      { icon: "camera", label: "Запись", value: "Прямая в Osmo" },
      { icon: "flight", label: "Автономность", value: "до 6 часов" },
      { icon: "distance", label: "Дальность", value: "до 250 м" },
      { icon: "video", label: "Сигнал", value: "Bluetooth + DJI Wireless" },
    ],
    techSpecs: [
      { label: "Тип", value: "Беспроводной передатчик BT/2.4" },
      { label: "Совместимость", value: "Osmo Action 5 Pro / Pocket 3 / Mic 2 RX" },
      { label: "Тип подключения", value: "Bluetooth 5.2 / DJI Wireless 2.4 ГГц" },
      { label: "Дальность", value: "до 250 м" },
      { label: "Шумоподавление", value: "Adaptive AI" },
      { label: "Частотный диапазон", value: "20 Гц – 20 кГц" },
      { label: "Внешний микрофон", value: "3.5 мм TRS" },
      { label: "Чувствительность", value: "−39 дБ" },
      { label: "Аккумулятор", value: "320 мА·ч" },
      { label: "Время работы", value: "до 6 часов" },
      { label: "Зарядка", value: "USB-C" },
      { label: "Защита от ветра", value: "Меховой колпак" },
      { label: "Масса", value: "30 г" },
      { label: "Размеры", value: "44 × 30 × 16 мм" },
      { label: "Сертификация", value: "CE, FCC, RoHS" },
    ],
  },
];

export default products;

export const PRODUCTS_BY_SLUG: Record<string, Product> = products.reduce(
  (acc, p) => {
    acc[p.slug] = p;
    return acc;
  },
  {} as Record<string, Product>,
);

export const PRODUCTS_BY_CATEGORY: Record<CatalogCategoryKey, Product[]> = products.reduce(
  (acc, p) => {
    (acc[p.category] ??= []).push(p);
    return acc;
  },
  {} as Record<CatalogCategoryKey, Product[]>,
);

export const getProductBySlug = (slug: string): Product | undefined => PRODUCTS_BY_SLUG[slug];
